[
  {
    table_name: 'connection',
    column_name: 'databasetypeId',
    data_type: 'integer',
    primary_key: null,
    foreign_key: 'foreign key',
    unique_key: null,
    referenced_table: 'databasetype',
    referenced_column: 'id',
  },
  {
    table_name: 'connection',
    column_name: 'dbHost',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'connection',
    column_name: 'dbName',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'connection',
    column_name: 'dbPassword',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'connection',
    column_name: 'dbPort',
    data_type: 'integer',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'connection',
    column_name: 'dbUsername',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'connection',
    column_name: 'description',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'connection',
    column_name: 'id',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'connection',
    column_name: 'name',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: 'unique key',
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'databasetype',
    column_name: 'id',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'databasetype',
    column_name: 'name',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: 'unique key',
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'databasetype',
    column_name: 'query',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'databasetype',
    column_name: 'type',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: 'unique key',
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'permission',
    column_name: 'id',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'permission',
    column_name: 'name',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: 'unique key',
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'role',
    column_name: 'id',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'role',
    column_name: 'name',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: 'unique key',
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'role',
    column_name: 'rank',
    data_type: 'integer',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'role_permissions_permission',
    column_name: 'permissionId',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: 'foreign key',
    unique_key: null,
    referenced_table: 'permission',
    referenced_column: 'id',
  },
  {
    table_name: 'role_permissions_permission',
    column_name: 'roleId',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: 'foreign key',
    unique_key: null,
    referenced_table: 'role',
    referenced_column: 'id',
  },
  {
    table_name: 'schema_column',
    column_name: 'alias',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'schema_column',
    column_name: 'dataType',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'schema_column',
    column_name: 'id',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'schema_column',
    column_name: 'schemaTableId',
    data_type: 'integer',
    primary_key: null,
    foreign_key: 'foreign key',
    unique_key: null,
    referenced_table: 'schema_table',
    referenced_column: 'id',
  },
  {
    table_name: 'schema_column',
    column_name: 'technicalName',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'schema_column_key',
    column_name: 'id',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'schema_column_key',
    column_name: 'type',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: 'unique key',
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'schema_column_key_column',
    column_name: 'id_column_key',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: 'foreign key',
    unique_key: null,
    referenced_table: 'schema_column_key',
    referenced_column: 'id',
  },
  {
    table_name: 'schema_column_key_column',
    column_name: 'id_schema_column',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: 'foreign key',
    unique_key: null,
    referenced_table: 'schema_column',
    referenced_column: 'id',
  },
  {
    table_name: 'schema_column_key_column',
    column_name: 'is_static',
    data_type: 'boolean',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'schema_relation',
    column_name: 'columnIdChild',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: 'foreign key',
    unique_key: null,
    referenced_table: 'schema_column',
    referenced_column: 'id',
  },
  {
    table_name: 'schema_relation',
    column_name: 'columnIdFather',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: 'foreign key',
    unique_key: null,
    referenced_table: 'schema_column',
    referenced_column: 'id',
  },
  {
    table_name: 'schema_relation',
    column_name: 'description',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'schema_relation',
    column_name: 'isStatic',
    data_type: 'boolean',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'schema_table',
    column_name: 'alias',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'schema_table',
    column_name: 'connectionId',
    data_type: 'integer',
    primary_key: null,
    foreign_key: 'foreign key',
    unique_key: null,
    referenced_table: 'connection',
    referenced_column: 'id',
  },
  {
    table_name: 'schema_table',
    column_name: 'description',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'schema_table',
    column_name: 'id',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'schema_table',
    column_name: 'technicalName',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'user',
    column_name: 'accountStatus',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'user',
    column_name: 'id',
    data_type: 'integer',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'user',
    column_name: 'name',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'user',
    column_name: 'password',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'user',
    column_name: 'username',
    data_type: 'character varying',
    primary_key: null,
    foreign_key: null,
    unique_key: null,
    referenced_table: null,
    referenced_column: null,
  },
  {
    table_name: 'user_permissions_permission',
    column_name: 'permissionId',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: 'foreign key',
    unique_key: null,
    referenced_table: 'permission',
    referenced_column: 'id',
  },
  {
    table_name: 'user_permissions_permission',
    column_name: 'userId',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: 'foreign key',
    unique_key: null,
    referenced_table: '"user"',
    referenced_column: 'id',
  },
  {
    table_name: 'user_roles_role',
    column_name: 'roleId',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: 'foreign key',
    unique_key: null,
    referenced_table: 'role',
    referenced_column: 'id',
  },
  {
    table_name: 'user_roles_role',
    column_name: 'userId',
    data_type: 'integer',
    primary_key: 'primary key',
    foreign_key: 'foreign key',
    unique_key: null,
    referenced_table: '"user"',
    referenced_column: 'id',
  },
];
