import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FeedbackContextProvider } from "@/contexts/feedback.context";
import { AuthProvider } from "@/contexts/AuthContext";
import { headers } from "next/headers";
import Sidebar from "@/components/nav/Sidebar";
import { Grid, Grid2 } from "@mui/material";
import ThemeRegistry from "@/components/theme/ThemeRegistry";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HABLAGUAI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerList = await headers();
  const userRoles = JSON.parse(headerList.get("x-user-roles") || "[]");
  console.log("layout.userRoles: ", userRoles);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <ThemeRegistry>
          <AuthProvider initialRoles={userRoles}>
            <FeedbackContextProvider>
              {/* <Grid2 container spacing={2} sx={{ flexGrow: 1 }}>
                <Grid2 size={3}></Grid2> */}
              <Grid2
                container
                sx={{ display: "flex", justifyContent: "center" }}
              >
                <Grid2
                  size={{
                    md: 2,
                    xs: 2,
                    sm: 0,
                    lg: 2,
                    xl: 2,
                  }}
                >
                  <Sidebar />
                </Grid2>
                <Grid2
                  size={8}
                  sx={{ marginTop: 6, xs: 8, sm: 8, md: 8, lg: 8, xl: 8 }}
                >
                  {children}
                </Grid2>
              </Grid2>
            </FeedbackContextProvider>
          </AuthProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
