import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FeedbackContextProvider } from "@/contexts/feedback.context";
import { AuthProvider } from "@/contexts/AuthContext";
import { headers } from "next/headers";
import Sidebar from "@/components/nav/Sidebar";
import { Grid, Grid2 } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerList = await headers();
  const userRoles = JSON.parse(headerList.get("x-user-roles") || "[]");
  console.log("layout.userRoles: ", userRoles);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <AuthProvider initialRoles={userRoles}>
          <FeedbackContextProvider>
            {/* <BasicLayoutNav initialRoles={userRoles}>{children}</BasicLayoutNav> */}
            {/* <MainNav /> */}
            <Grid2 container>
              <Grid2 size={3}>
                <Sidebar />
              </Grid2>
              <Grid2 size={8} sx={{ marginTop: 6 }}>
                {children}
              </Grid2>
            </Grid2>
          </FeedbackContextProvider>
        </AuthProvider>
        {/* <main className="flex-grow flex justify-center w-full"></main> */}
      </body>
    </html>
  );
}
