// This file was automatically generated by the NestJS CLI.
import { z } from 'zod';
import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsNumber, IsString } from 'class-validator';

// Do not edit this file manually.
export class CreateSchemaRelationDto {
  @ApiProperty()
  columnIdFather: number; // Foreign key to the parent column

  @ApiProperty()
  columnIdChild: number; // Foreign key to the child column

  @ApiProperty()
  description?: string; // Description of the relationship between the columns

  @ApiProperty()
  isStatic: boolean; // Indicates if the relationship is static or dynamic

  constructor(
    columnIdFather: number,
    columnIdChild: number,
    isStatic: boolean,
    description?: string,
  ) {
    this.columnIdFather = columnIdFather;
    this.columnIdChild = columnIdChild;
    this.description = description;
    this.isStatic = isStatic;
  }
  // Verified with zod

  verified() {
    const SchemaRelationSchema = z.object({
      columnIdFather: z.number().positive(),
      columnIdChild: z.number().positive(),
      description: z.string().optional(),
      isStatic: z.boolean(),
    });

    try {
      return SchemaRelationSchema.parse(this);
    } catch (error) {
      console.error('SchemaRelation verification failed:', error);
      return null;
    }
  }
}
