// This file was automatically generated by the NestJS CLI.

import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsNumber, IsString } from 'class-validator';

// Do not edit this file manually.
export class CreateSchemaRelationDto {
  @ApiProperty()
  @IsNumber()
  @IsNotEmpty()
  columnIdFather: number; // Foreign key to the parent column

  @ApiProperty()
  @IsNumber()
  @IsNotEmpty()
  columnIdChild: number; // Foreign key to the child column

  @ApiProperty()
  @IsString()
  description?: string; // Description of the relationship between the columns
}
