export const schemaCtxDiff = [
  {
    id: "tmprd",
    name: "tmprd",
    tables: [
      {
        id: "tmprd.nnr300",
        name: "nnr300",
        columns: [
          {
            id: "tmprd.nnr300.nnr_cod",
            name: "nnr_cod",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.nnr300.nnr_descri",
            name: "nnr_descri",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
        ],
        status: 0,
        oldId: "",
        oldName: "",
        newId: "",
        newName: "",
      },
      {
        id: "tmprd.pb7300",
        name: "pb7300",
        columns: [
          {
            id: "tmprd.pb7300.pb7_pedido",
            name: "pb7_pedido",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_cod_cliente",
            name: "pb7_cod_cliente",
            dataType: {
              name: "numeric",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.pb7300.pb7_cliente",
            oldName: "pb7_cliente",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_produt",
            name: "pb7_produt",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_itempv",
            name: "pb7_itempv",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_filial",
            name: "pb7_filial",
            dataType: {
              name: "character varying",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_sequen",
            name: "pb7_sequen",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_data",
            name: "pb7_data",
            dataType: {
              name: "date",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_dsaida",
            name: "pb7_dsaida",
            dataType: {
              name: "date",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_qtde",
            name: "pb7_qtde",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_status",
            name: "pb7_status",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_pbruto",
            name: "pb7_pbruto",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_ptara",
            name: "pb7_ptara",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_placa",
            name: "pb7_placa",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_chofer",
            name: "pb7_chofer",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_telefo",
            name: "pb7_telefo",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_docume",
            name: "pb7_docume",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_xdesp",
            name: "pb7_xdesp",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_locent",
            name: "pb7_locent",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_xzafra",
            name: "pb7_xzafra",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_observ",
            name: "pb7_observ",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_xobs",
            name: "pb7_xobs",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300.pb7_cliente",
            name: "pb7_cliente",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.pb7300.pb7_cod_cliente",
            newName: "pb7_cod_cliente",
          },
        ],
        status: 0,
        oldId: "",
        oldName: "",
        newId: "",
        newName: "",
      },
      {
        id: "tmprd.pb7300_hist",
        name: "pb7300_hist",
        columns: [
          {
            id: "tmprd.pb7300_hist.id_hist",
            name: "id_hist",
            dataType: {
              name: "bigint",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 1,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300_hist.pb7_pedido",
            name: "pb7_pedido",
            dataType: {
              name: "numeric",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 1,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300_hist.pb7_sequen",
            name: "pb7_sequen",
            dataType: {
              name: "numeric",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 1,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300_hist.fecha_evento",
            name: "fecha_evento",
            dataType: {
              name: "timestamp without time zone",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 1,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300_hist.estado_anterior",
            name: "estado_anterior",
            dataType: {
              name: "character varying",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 1,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300_hist.estado_nuevo",
            name: "estado_nuevo",
            dataType: {
              name: "character varying",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 1,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.pb7300_hist.usuario",
            name: "usuario",
            dataType: {
              name: "character varying",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 1,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
        ],
        status: 1,
        oldId: "",
        oldName: "",
        newId: "",
        newName: "",
      },
      {
        id: "tmprd.sa1300",
        name: "sa1300",
        columns: [
          {
            id: "tmprd.sa1300.a1_cod",
            name: "a1_cod",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sa1300.a1_nome",
            name: "a1_nome",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sa1300.a1_cgc",
            name: "a1_cgc",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sa1300.a1_utpcli",
            name: "a1_utpcli",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sa1300.a1_loja",
            name: "a1_loja",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
        ],
        status: 0,
        oldId: "",
        oldName: "",
        newId: "",
        newName: "",
      },
      {
        id: "tmprd.sb1300",
        name: "sb1300",
        columns: [
          {
            id: "tmprd.sb1300.b1_cod_change",
            name: "b1_cod_change",
            dataType: {
              name: "character varying",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sb1300.b1_cod",
            oldName: "b1_cod",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sb1300.b1_desc",
            name: "b1_desc",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sb1300.b1_um",
            name: "b1_um",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sb1300.b1_cod",
            name: "b1_cod",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sb1300.b1_cod_change",
            newName: "b1_cod_change",
          },
        ],
        status: 0,
        oldId: "",
        oldName: "",
        newId: "",
        newName: "",
      },
      {
        id: "tmprd.sc5300",
        name: "sc5300",
        columns: [
          {
            id: "tmprd.sc5300.c5_num",
            name: "c5_num",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc5300.c5_cliente",
            name: "c5_cliente",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc5300.c5_emissao",
            name: "c5_emissao",
            dataType: {
              name: "date",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc5300.c5_xtipo",
            name: "c5_xtipo",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc5300.c5_moeda",
            name: "c5_moeda",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc5300.c5_lojacli",
            name: "c5_lojacli",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
        ],
        status: 0,
        oldId: "",
        oldName: "",
        newId: "",
        newName: "",
      },
      {
        id: "tmprd.sc6301",
        name: "sc6301",
        columns: [
          {
            id: "tmprd.sc6301.c6_id_change",
            name: "c6_id_change",
            dataType: {
              name: "character varying",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_id",
            oldName: "c6_id",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_num",
            name: "c6_num",
            dataType: {
              name: "numeric",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_num",
            oldName: "c6_num",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_item",
            name: "c6_item",
            dataType: {
              name: "numeric",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_item",
            oldName: "c6_item",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_produto",
            name: "c6_produto",
            dataType: {
              name: "character varying",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_produto",
            oldName: "c6_produto",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_descri",
            name: "c6_descri",
            dataType: {
              name: "character varying",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_descri",
            oldName: "c6_descri",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_um",
            name: "c6_um",
            dataType: {
              name: "character varying",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_um",
            oldName: "c6_um",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_qtdven",
            name: "c6_qtdven",
            dataType: {
              name: "numeric",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_qtdven",
            oldName: "c6_qtdven",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_qtdent",
            name: "c6_qtdent",
            dataType: {
              name: "numeric",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_qtdent",
            oldName: "c6_qtdent",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_prcven",
            name: "c6_prcven",
            dataType: {
              name: "numeric",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_prcven",
            oldName: "c6_prcven",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_valor",
            name: "c6_valor",
            dataType: {
              name: "numeric",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_valor",
            oldName: "c6_valor",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_tes",
            name: "c6_tes",
            dataType: {
              name: "numeric",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_tes",
            oldName: "c6_tes",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_local",
            name: "c6_local",
            dataType: {
              name: "numeric",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_local",
            oldName: "c6_local",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_localdest",
            name: "c6_localdest",
            dataType: {
              name: "numeric",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_localdest",
            oldName: "c6_localdest",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_cli",
            name: "c6_cli",
            dataType: {
              name: "numeric",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_cli",
            oldName: "c6_cli",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_loja",
            name: "c6_loja",
            dataType: {
              name: "character varying",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_loja",
            oldName: "c6_loja",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_filial",
            name: "c6_filial",
            dataType: {
              name: "numeric",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sc6300.c6_filial",
            oldName: "c6_filial",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc6301.c6_obs",
            name: "c6_obs",
            dataType: {
              name: "character varying",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 1,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
        ],
        status: 3,
        oldId: "tmprd.sc6300",
        oldName: "sc6300",
        newId: "",
        newName: "",
      },
      {
        id: "tmprd.sc9300",
        name: "sc9300",
        columns: [
          {
            id: "tmprd.sc9300.c9_id",
            name: "c9_id",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc9300.c9_pedido",
            name: "c9_pedido",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc9300.c9_cliente",
            name: "c9_cliente",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc9300.c9_produto",
            name: "c9_produto",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc9300.c9_item",
            name: "c9_item",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc9300.c9_local",
            name: "c9_local",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc9300.c9_filial",
            name: "c9_filial",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc9300.c9_sequen",
            name: "c9_sequen",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc9300.c9_datalib",
            name: "c9_datalib",
            dataType: {
              name: "date",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sc9300.c9_status",
            name: "c9_status",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
        ],
        status: 0,
        oldId: "",
        oldName: "",
        newId: "",
        newName: "",
      },
      {
        id: "tmprd.sd2300",
        name: "sd2300",
        columns: [
          {
            id: "tmprd.sd2300.d2_tipodoc",
            name: "d2_tipodoc",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_numero_doc",
            name: "d2_numero_doc",
            dataType: {
              name: "numeric",
              status: 1,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "tmprd.sd2300.d2_doc",
            oldName: "d2_doc",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_serie",
            name: "d2_serie",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_remito",
            name: "d2_remito",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_serirem",
            name: "d2_serirem",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_item",
            name: "d2_item",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_itempv",
            name: "d2_itempv",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_itemrem",
            name: "d2_itemrem",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_dtdigit",
            name: "d2_dtdigit",
            dataType: {
              name: "date",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_cliente",
            name: "d2_cliente",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_loja",
            name: "d2_loja",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_filial",
            name: "d2_filial",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_pedido",
            name: "d2_pedido",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_cod",
            name: "d2_cod",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_sequen",
            name: "d2_sequen",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_um",
            name: "d2_um",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_quant",
            name: "d2_quant",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_qtsegum",
            name: "d2_qtsegum",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_prcven",
            name: "d2_prcven",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_total",
            name: "d2_total",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_tes",
            name: "d2_tes",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_custo1",
            name: "d2_custo1",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_local",
            name: "d2_local",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_emissao",
            name: "d2_emissao",
            dataType: {
              name: "date",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_grupo",
            name: "d2_grupo",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_conta",
            name: "d2_conta",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_valimp5",
            name: "d2_valimp5",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd2300.d2_doc",
            name: "d2_doc",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sd2300.d2_numero_doc",
            newName: "d2_numero_doc",
          },
        ],
        status: 0,
        oldId: "",
        oldName: "",
        newId: "",
        newName: "",
      },
      {
        id: "tmprd.sd3300",
        name: "sd3300",
        columns: [
          {
            id: "tmprd.sd3300.d3_cod",
            name: "d3_cod",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd3300.d3_doc",
            name: "d3_doc",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd3300.d3_xnrotra",
            name: "d3_xnrotra",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd3300.d3_um",
            name: "d3_um",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd3300.d3_quant",
            name: "d3_quant",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd3300.d3_qtsegum",
            name: "d3_qtsegum",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd3300.d3_local",
            name: "d3_local",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd3300.d3_filial",
            name: "d3_filial",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd3300.d3_almdest",
            name: "d3_almdest",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd3300.d3_emissao",
            name: "d3_emissao",
            dataType: {
              name: "date",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd3300.d3_tm",
            name: "d3_tm",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd3300.d3_xorigen",
            name: "d3_xorigen",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd3300.d3_usuario",
            name: "d3_usuario",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sd3300.d3_estorno",
            name: "d3_estorno",
            dataType: {
              name: "character varying",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 2,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
        ],
        status: 0,
        oldId: "",
        oldName: "",
        newId: "",
        newName: "",
      },
      {
        id: "tmprd.se4300",
        name: "se4300",
        columns: [
          {
            id: "tmprd.se4300.e4_codigo",
            name: "e4_codigo",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.se4300.e4_tipo",
            name: "e4_tipo",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.se4300.e4_descri",
            name: "e4_descri",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
        ],
        status: 0,
        oldId: "",
        oldName: "",
        newId: "",
        newName: "",
      },
      {
        id: "tmprd.sf2300",
        name: "sf2300",
        columns: [
          {
            id: "tmprd.sf2300.f2_doc",
            name: "f2_doc",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sf2300.f2_serie",
            name: "f2_serie",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sf2300.f2_dtdigit",
            name: "f2_dtdigit",
            dataType: {
              name: "date",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sf2300.f2_cliente",
            name: "f2_cliente",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sf2300.f2_loja",
            name: "f2_loja",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sf2300.f2_moeda",
            name: "f2_moeda",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sf2300.f2_numaut",
            name: "f2_numaut",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sf2300.f2_codctr",
            name: "f2_codctr",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sf2300.f2_unit",
            name: "f2_unit",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sf2300.f2_unome",
            name: "f2_unome",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sf2300.f2_upedido",
            name: "f2_upedido",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sf2300.f2_uglosa",
            name: "f2_uglosa",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sf2300.f2_cond",
            name: "f2_cond",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sf2300.f2_emissao",
            name: "f2_emissao",
            dataType: {
              name: "date",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sf2300.f2_valbrut",
            name: "f2_valbrut",
            dataType: {
              name: "numeric",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
        ],
        status: 0,
        oldId: "",
        oldName: "",
        newId: "",
        newName: "",
      },
      {
        id: "tmprd.sza300",
        name: "sza300",
        columns: [
          {
            id: "tmprd.sza300.sz_custocod",
            name: "sz_custocod",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sza300.sz_clicompnom",
            name: "sz_clicompnom",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sza300.sz_clicontacnom",
            name: "sz_clicontacnom",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sza300.sz_clicontat",
            name: "sz_clicontat",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sza300.sz_clidirecc",
            name: "sz_clidirecc",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sza300.sz_cliciud",
            name: "sz_cliciud",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sza300.sz_clreg",
            name: "sz_clreg",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sza300.sz_clienpost",
            name: "sz_clienpost",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sza300.sz_custpai",
            name: "sz_custpai",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sza300.sz_telf",
            name: "sz_telf",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.sza300.sz_fa",
            name: "sz_fa",
            dataType: {
              name: "character varying",
              status: 0,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 0,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
        ],
        status: 0,
        oldId: "",
        oldName: "",
        newId: "",
        newName: "",
      },
      {
        id: "tmprd.sc6300",
        name: "sc6300",
        columns: [
          {
            id: "tmprd.sc6300.c6_id",
            name: "c6_id",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_id_change",
            newName: "c6_id_change",
          },
          {
            id: "tmprd.sc6300.c6_num",
            name: "c6_num",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_num",
            newName: "c6_num",
          },
          {
            id: "tmprd.sc6300.c6_item",
            name: "c6_item",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_item",
            newName: "c6_item",
          },
          {
            id: "tmprd.sc6300.c6_produto",
            name: "c6_produto",
            dataType: {
              name: "character varying",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_produto",
            newName: "c6_produto",
          },
          {
            id: "tmprd.sc6300.c6_descri",
            name: "c6_descri",
            dataType: {
              name: "character varying",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_descri",
            newName: "c6_descri",
          },
          {
            id: "tmprd.sc6300.c6_um",
            name: "c6_um",
            dataType: {
              name: "character varying",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_um",
            newName: "c6_um",
          },
          {
            id: "tmprd.sc6300.c6_qtdven",
            name: "c6_qtdven",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_qtdven",
            newName: "c6_qtdven",
          },
          {
            id: "tmprd.sc6300.c6_qtdent",
            name: "c6_qtdent",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_qtdent",
            newName: "c6_qtdent",
          },
          {
            id: "tmprd.sc6300.c6_prcven",
            name: "c6_prcven",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_prcven",
            newName: "c6_prcven",
          },
          {
            id: "tmprd.sc6300.c6_valor",
            name: "c6_valor",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_valor",
            newName: "c6_valor",
          },
          {
            id: "tmprd.sc6300.c6_tes",
            name: "c6_tes",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_tes",
            newName: "c6_tes",
          },
          {
            id: "tmprd.sc6300.c6_local",
            name: "c6_local",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_local",
            newName: "c6_local",
          },
          {
            id: "tmprd.sc6300.c6_localdest",
            name: "c6_localdest",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_localdest",
            newName: "c6_localdest",
          },
          {
            id: "tmprd.sc6300.c6_cli",
            name: "c6_cli",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_cli",
            newName: "c6_cli",
          },
          {
            id: "tmprd.sc6300.c6_loja",
            name: "c6_loja",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_loja",
            newName: "c6_loja",
          },
          {
            id: "tmprd.sc6300.c6_filial",
            name: "c6_filial",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 3,
            oldId: "",
            oldName: "",
            newId: "tmprd.sc6301.c6_filial",
            newName: "c6_filial",
          },
        ],
        status: 3,
        oldId: "",
        oldName: "",
        newId: "tmprd.sc6301",
        newName: "sc6301",
      },
      {
        id: "tmprd.szg300",
        name: "szg300",
        columns: [
          {
            id: "tmprd.szg300.zg_codigo",
            name: "zg_codigo",
            dataType: {
              name: "numeric",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 2,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
          {
            id: "tmprd.szg300.zg_desc",
            name: "zg_desc",
            dataType: {
              name: "character varying",
              status: 2,
              oldId: "",
              oldName: "",
              newId: "",
              newName: "",
            },
            status: 2,
            oldId: "",
            oldName: "",
            newId: "",
            newName: "",
          },
        ],
        status: 2,
        oldId: "",
        oldName: "",
        newId: "",
        newName: "",
      },
    ],
    status: 0,
    oldId: "",
    oldName: "",
    newId: "",
    newName: "",
  },
];
